### ISSUE TITLE
Meltan & Melmetal lines can't be referenced

### ISSUE THREAD

**Issue by jessicayyu** [ytakahashi/pokedex.js#27]
Neither the names nor the pokedex numbers seem to return anything when I try to query the library. The rest of gen 8 seems to work, but Meltan and Melmetal return an empty [].

**Comment by ytakahashi** [comment]
Thank you for reporting.
Yes, they are not included in this Pokédex now... because they were introduced in Pokémon Go and not in game series. 
I was not sure where they belongs within the Pokémon generations.

I was expecting Pokémon Home cloud resolve this, but it didn't work out like that as in [this article](https://www.cbr.com/pokemon-meltan-generation/).

I checked some webpages (like [pokemondb](https://pokemondb.net/pokedex/melmetal) or [wikipedia](https://en.wikipedia.org/wiki/Meltan_and_Melmetal)) and found they are classified as Generation 7 Pokémon, so I added them as Gen 7 Pokémon in https://github.com/ytakahashi/pokedex.js/pull/28 and published as `3.3.0`.
