### ISSUE TITLE
Name and Galar IDs

### ISSUE THREAD

**Issue by jessicayyu** [ytakahashi/pokedex.js#33]
Hi, I've found a few missing things:  
  
- Koffing & Weezing (Kanto form) has 3 possible abilities this generation: Levitate, Neutralizing Gas, and HA Stench.   
- Zigzagoon & Linoone don't seem to have their Galar IDs registered. [Zigzagoon is #031](https://www.serebii.net/pokedex-swsh/zigzagoon/), [Linoone is #032](https://www.serebii.net/pokedex-swsh/linoone/).  
- Farfetch'd seems to be missing a Galar ID, too. [The Galar ID is #218](https://www.serebii.net/pokedex-swsh/farfetch'd/)
- 689 Barbacle should be spelled Barbaracle. [Serebii dex entry here.](https://www.serebii.net/pokedex-swsh/barbaracle/)  
   
If you would be able to add these in when you have time, that would be wonderful. Thanks for all your hard work!

**Comment by ytakahashi** [comment]
Thanks for your report! I fixed missing abilities of Koffing & Weezing and spelling of Barbaracle and published as version `3.3.3`.

As for Galar IDs, yes, original form of Zigzagoon, Linoone and Farfetch'd do not have galarId.

It's because Pokédex in Pokémon Sword and Shield only lists Galarian form of them (and original ones were not available at first).

You can find 'gararId' in their Galarian Form as follows:

```javascript
console.log(pokedex.name('Zigzagoon').get())
// [{"id":"263","name":"Zigzagoon","type":["Normal"],"ability":[{"name":"Pickup","hidden":false},{"name":"Gluttony","hidden":false},{"name":"Quick Feet","hidden":true}],"eggGroup":["Field"],"baseStats":{"H":"38","A":"30","B":"41","C":"30","D":"41","S":"60"},"generation":3},{"id":"263","formName":"Galarian Form","localId":{"galar":"31"},"name":"Zigzagoon","type":["Dark","Normal"],"ability":[{"name":"Pickup","hidden":false},{"name":"Gluttony","hidden":false},{"name":"Quick Feet","hidden":true}],"eggGroup":["Field"],"baseStats":{"H":"38","A":"30","B":"41","C":"30","D":"41","S":"60"},"generation":8}]
```

```javascript
console.log(pokedex.name('Zigzagoon').inGalarPokedex().get())
// [{"id":"263","formName":"Galarian Form","localId":{"galar":"31"},"name":"Zigzagoon","type":["Dark","Normal"],"ability":[{"name":"Pickup","hidden":false},{"name":"Gluttony","hidden":false},{"name":"Quick Feet","hidden":true}],"eggGroup":["Field"],"baseStats":{"H":"38","A":"30","B":"41","C":"30","D":"41","S":"60"},"generation":8}]
```

and "galarId" should be assigned to all Pokemon in Pokémon Sword and Shield Pokédex.

Thank you!
